In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, roc_curve, auc
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
x_train = np.array(['Chinese Beijing Chinese',
                   'Chinese Chinese Shanghai',
                   'Chinese Macao',
                   'Tokyo Japan Chinese'])

y_train = np.array(['china','china','china','not china'])

x_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

In [3]:
vect = CountVectorizer(binary=True)

In [4]:
x_train_dtm = vect.fit_transform(x_train)

print(vect.get_feature_names())
print(x_train_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 1 0 0 0 0]
 [0 1 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [5]:
x_test_dtm = vect.transform(x_test)

print(x_test_dtm.toarray())

[[0 1 1 0 0 1]]


In [6]:
model = BernoulliNB(binarize=None)

In [7]:
model.fit(x_train_dtm, y_train)

BernoulliNB(alpha=1.0, binarize=None, class_prior=None, fit_prior=True)

In [8]:
y_pred_class = model.predict(x_test_dtm)

print(y_pred_class)
print(model.predict_proba(x_test_dtm))

['not china']
[[0.19106679 0.80893321]]
